FROM node:14.18-alpine 

# RUN apk add --no-cache python2 g++ make

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./

# RUN apk --no-cache --virtual build-dependencies add \
#         python2 \
#         make \
#         g++
RUN yarn install

COPY . ./

CMD ["yarn", "start:developmentsbx"]
