export const useStyles = ({ isSearcheable = false, classes = {} } = {}) => ({
  container: (provided) => ({
    ...provided,
    position: 'relative',
    width: '100%',
    height: '100%',

    ...classes.container,
  }),
  control: (provided) => ({
    ...provided,
    position: 'relative',
    width: '100%',
    height: 46,
    cursor: isSearcheable ? 'pointer' : 'text',
    appearance: 'none',
    background: 'white',
    border: '1px solid #ccc',
    borderRadius: 3,
    boxShadow: 'none',
    '&:hover': { borderColor: '#000' },
    ...classes.control,
  }),
  valueContainer: (provided) => ({
    ...provided,
    position: 'relative',
    boxSizing: 'border-box',
    color: '#000',
    fontSize: 16,
    outline: 'none',
    transition: 'all 0.2s ease-in-out',
    width: '100%',
    height: '100%',
    caret: isSearcheable ? 'block' : 'none',
    cursor: isSearcheable ? 'text' : 'pointer',
    display: 'flex',
    alignItems: 'center',
    padding: 0,
    margin: 0,
    ...classes.valueContainer,
  }),
  placeholder: () => ({
    fontFamily: 'Brown SemiBold',
    fontWeight: 100,
    color: '#999',
    fontSize: 10,
    paddingLeft: 9,
    top: 3,
    cursor: 'text',
    position: 'absolute',
    transition: 'all 0.2s',

    span: {
      color: '#d65b53',
      display: 'inline-block',
      paddingLeft: 5,
    },
    ...classes.placeholder,
  }),
  indicatorSeparator: (provided) => ({
    ...provided,
    display: 'none',
  }),
  singleValue: (provided, state) => ({
    ...provided,
    width: '100%',
    maxWidth: '100%',
    padding: '19px 0 0 10px',
    lineHeight: '19px',
    height: '100%',
    margin: 0,
    fontSize: 14,
    color: state.data?.isDefault ? '#888' : '#000',
    ...classes.singleValue,
  }),
  dropdownIndicator: (provided, state) => ({
    ...provided,
    cursor: 'pointer',
    color: '#000',
    transition: 'all 0.4s',
    transform: state.selectProps.menuIsOpen ? 'rotate(180deg)' : 'rotate(0deg)',
  }),
  input: (provided) => ({
    ...provided,
    height: '100%',
    width: '100%',
    padding: 0,
    position: 'relative',
    fontSize: 14,
    lineHeight: '14px',
    margin: 0,

    div: {
      top: 0,
      height: '100%',
      padding: '11px 0 0 10px',
      width: '100%',

      input: {
        fontFamily: 'Gilroy Light',
        position: 'absolute',
        top: 18,

        '&::focus': {
          backgroundColor: 'white',
        },
      },
    },
    ...classes.input,
  }),
  menu: (provided, state) => ({
    ...provided,
    zIndex: 10,
    marginTop: state.getValue()[0]?.isDefault ? 4 : 0,
    ...classes.menu,
  }),
  menuPortal: ({ ...provided }) => ({
    ...provided,
    position: 'absolute',
    zIndex: 100,
  }),
  option: (provider, state) => ({
    ...provider,
    display: state.data?.isDefault ? 'none' : 'block',
    cursor: 'pointer',
    fontSize: 14,
    lineHeight: '14px',
  }),
})
