'on':
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      TESTING_ENABLED:
        default: 'true'
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PRIVATE_REPO_ACCESS:
        required: true

name: Testing Cypress
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        if: ${{ inputs.TESTING_ENABLED != 'false' }}
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          config-file: cypress/${{ inputs.ENVIRONMENT }}-cypress.config.js
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: false
          group: "Frontend - Chrome"
          tag: ${{ inputs.ENVIRONMENT }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS }}
