on:
  workflow_call:
    inputs:
      TESTING_ENABLED:
        required: false
        default: "true"
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PRIVATE_REPO_ACCESS:
        required: true

name: Testing Cypress
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ inputs. TESTING_ENABLED == 'true' }}
        uses: actions/checkout@v2
      - name: Cypress run
        if:
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
